### ISSUE TITLE
Problem with the sum of cells filtered

### ISSUE THREAD

**Issue by Gregjlt** [vallotlab/ChromSCape#10]
The number of total cells that passed the filters is different from what it should be. 
![path826](https://user-images.githubusercontent.com/117280379/200349230-5540a05e-7899-4f8c-a07b-197501339f2c.png)

**Comment by Pacomito** [comment]
This is now corrected in [fcd9b02](https://github.com/vallotlab/ChromSCape/commit/fcd9b021e5b6c67003e9ac05af8ce68bd6d37c6e).
