### ISSUE TITLE
How to use ChromSCape to analyze scATAC-seq data from 10x Genomics？

### ISSUE THREAD

**Issue by zhangdudu0** [vallotlab/ChromSCape#16]
![image](https://github.com/vallotlab/ChromSCape/assets/78540610/e8e65c3e-ece5-4e23-af2e-12e2a764b70f)
I used the cellranger software from 10x Genomics for upstream analysis. I selected the out directory from the cellranger output as the Selected Folder, but a yellow popup window appeared in the bottom right corner, saying that it couldn't find the sparse matrix. I want to ask, what format does this sparse matrix need to be in? It would be even better if you could provide a complete scATAC-seq analysis process using ChromSCape.
![image](https://github.com/vallotlab/ChromSCape/assets/78540610/1142ed95-f816-4026-ae5d-e1e0ee921918)

**Comment by Pacomito** [comment]
Dear Zhangdudu, 
sorry for the delayed answer,

Could you display the naming of the files in the filtered_peak_bc_matrix/ folder  ?

When you select the folder, are you correctly selecting lhj7_cellranger-atac/**outs/** ? Then in the  "Selected samples" display the app should show three folders: _filtered_peak_bc_matrix_, _filtered_tf_bc_matrix_ and _raw_peak_bc_matrix_ and you have to keep only the _filtered_peak_bc_matrix_ folder.

Thank you for your suggestion, I will try to make a quick tutorial for scATAC-seq.

Best,
Pacôme

**Comment by Pacomito** [comment]
Dear Zhangdudu,

Did this work ?

I think the function could not read the peaks.bed format from 10X.  I modified the code yesterday and tried on a 10X matrix and tested on a 10X dataset, so you might want to give it a try, by re-installing the latest version:

`devtools::install_github("vallotlab/ChromSCape")`.

Best,
Pacôme
