### ISSUE TITLE
ChromScape availability on R.3.6.3

### ISSUE THREAD

**Issue by Cala3len** [vallotlab/ChromSCape#2]
Hello Pacome,

I am getting this error when trying to install Chromscape on R.3.6.3 running 

`devtools::install_github("vallotlab/ChromSCape")` :
```
Installing package into ‘/home/cbenoit/installbioshlibtest2/renv/library/R-3.6/x86_64-pc-linux-gnu’
(as ‘lib’ is unspecified)
ERREUR : cette version de R est 3.6.3, le package 'ChromSCape'  nécessite R >= 4.0
Erreur : Failed to install 'ChromSCape' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/RtmpYxrT3U/file451f4e3a08fb/ChromSCape_0.99.011.tar.gz’ had non-zero exit status
```

Best wishes,

Cala3len

**Comment by Pacomito** [comment]
Hello Cala3len,

ChromSCape is now only available on R4.02, and will be avaialble on BioConductor on next release (3.12), 
I will modify the ReadMe file accordingly,

Cheers,
Pacôme
